<a href="https://colab.research.google.com/github/sanchitasontakke07-exe/Day25-optional-/blob/main/Day25(optional).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from google.colab import files
uploaded=files.upload()
df=pd.read_csv("student_record.csv")
print("Dataset Loaded Successfully")

Saving student_record.csv to student_record (3).csv
Dataset Loaded Successfully

In [6]:
df

,StudentID,Gender,Age,MotherEducation,FatherEducation,StudyTime,PreviousFailures,Internet,Extracurricular,Absences,Midterm1,Midterm2,FinalScore,Attendance,Result
0,ST0001,F,18,4,4,2,0,no,no,4,0,11,11,96,Pass
1,ST0002,F,17,1,1,2,0,yes,no,2,9,11,11,98,Pass
2,ST0003,F,15,1,1,2,0,yes,no,6,12,13,12,94,Pass
3,ST0004,F,15,4,2,3,0,yes,yes,0,14,14,14,100,Pass
4,ST0005,F,16,3,3,2,0,no,no,0,11,13,13,100,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,ST0645,F,19,2,3,3,1,yes,yes,4,10,11,10,96,Pass
645,ST0646,F,18,3,1,2,0,yes,no,4,15,15,16,96,Pass
646,ST0647,F,18,1,1,2,0,no,yes,6,11,12,9,94,Fail
647,ST0648,M,17,3,1,1,0,yes,no,6,10,10,10,94,Pass
648,ST0649,M,18,3,2,1,0,yes,no,4,10,11,11,96,Pass

In [16]:
print(df.shape)

(649, 15)

In [17]:
print(df.columns)

Index(['StudentID', 'Gender', 'Age', 'MotherEducation', 'FatherEducation',
       'StudyTime', 'PreviousFailures', 'Internet', 'Extracurricular',
       'Absences', 'Midterm1', 'Midterm2', 'FinalScore', 'Attendance',
       'Result'],
      dtype='object')

In [18]:
print(df.dtypes)

StudentID           int64
Gender              int64
Age                 int64
MotherEducation     int64
FatherEducation     int64
StudyTime           int64
PreviousFailures    int64
Internet            int64
Extracurricular     int64
Absences            int64
Midterm1            int64
Midterm2            int64
FinalScore          int64
Attendance          int64
Result              int64
dtype: object

In [7]:
df.isnull().sum()

StudentID           0
Gender              0
Age                 0
MotherEducation     0
FatherEducation     0
StudyTime           0
PreviousFailures    0
Internet            0
Extracurricular     0
Absences            0
Midterm1            0
Midterm2            0
FinalScore          0
Attendance          0
Result              0
dtype: int64

In [9]:
# Handle Missing Values
if df.isnull().sum().sum() == 0:
    print("No missing values found.")
else:
    # Fill numerical columns with mean
    df.fillna(df.mean(numeric_only=True), inplace=True)

    # Fill categorical columns with mode
    for column in df.select_dtypes(include='object').columns:
        df[column].fillna(df[column].mode()[0], inplace=True)
print(df.isnull().sum())

No missing values found.
StudentID           0
Gender              0
Age                 0
MotherEducation     0
FatherEducation     0
StudyTime           0
PreviousFailures    0
Internet            0
Extracurricular     0
Absences            0
Midterm1            0
Midterm2            0
FinalScore          0
Attendance          0
Result              0
dtype: int64

In [10]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include="object"):
    df[col] = le.fit_transform(df[col])

df.head()

,StudentID,Gender,Age,MotherEducation,FatherEducation,StudyTime,PreviousFailures,Internet,Extracurricular,Absences,Midterm1,Midterm2,FinalScore,Attendance,Result
0,0,0,18,4,4,2,0,0,0,4,0,11,11,96,1
1,1,0,17,1,1,2,0,1,0,2,9,11,11,98,1
2,2,0,15,1,1,2,0,1,0,6,12,13,12,94,1
3,3,0,15,4,2,3,0,1,1,0,14,14,14,100,1
4,4,0,16,3,3,2,0,0,0,0,11,13,13,100,1

In [12]:
# Select Features and Target
X = df.drop(["StudentID", "FinalScore", "Result"], axis=1)
y = df["Result"]
print("Features:")
print(X.head())
print("\nTarget:")
print(y.head())

Features:
   Gender  Age  MotherEducation  FatherEducation  StudyTime  PreviousFailures  \
0       0   18                4                4          2                 0
1       0   17                1                1          2                 0
2       0   15                1                1          2                 0
3       0   15                4                2          3                 0
4       0   16                3                3          2                 0

   Internet  Extracurricular  Absences  Midterm1  Midterm2  Attendance
0         0                0         4         0        11          96
1         1                0         2         9        11          98
2         1                0         6        12        13          94
3         1                1         0        14        14         100
4         0                0         0        11        13         100

Target:
0    1
1    1
2    1
3    1
4    1
Name: Result, dtype: int64

In [82]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [15]:
# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)

(519, 12)
(130, 12)

In [26]:
# Manual Hyperparameter Tuning - KNN

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

neighbors = [3, 5, 7, 9, 11]

for k in neighbors:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    print(f"K = {k}  --> Accuracy = {accuracy:.4f}")

K = 3  --> Accuracy = 0.9000
K = 5  --> Accuracy = 0.8923
K = 7  --> Accuracy = 0.9000
K = 9  --> Accuracy = 0.9000
K = 11  --> Accuracy = 0.9000

In [43]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN = KNeighborsClassifier(n_neighbors=7)
model_KNN.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [39]:
model_KNN.score(X_test, y_test)

0.9

In [41]:
model_KNN = KNeighborsClassifier(n_neighbors=15)
model_KNN.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [42]:
model_KNN.score(X_test, y_test)

0.9076923076923077

In [50]:
from sklearn.svm import SVC

parameters = [
    (1, "linear"),
    (1, "rbf"),
    (10, "linear"),
    (10, "rbf"),
    (20, "linear"),
    (20, "rbf")
]

for c, kernel in parameters:

    model_SVM = SVC(C=c, kernel=kernel)

    model_SVM.fit(X_train, y_train)

    test_accuracy = model_SVM.score(X_test, y_test)

    print("C =", c, "| Kernel =", kernel, "| Accuracy =", test_accuracy)

C = 1 | Kernel = linear | Accuracy = 0.9153846153846154
C = 1 | Kernel = rbf | Accuracy = 0.9
C = 10 | Kernel = linear | Accuracy = 0.9153846153846154
C = 10 | Kernel = rbf | Accuracy = 0.9
C = 20 | Kernel = linear | Accuracy = 0.9153846153846154
C = 20 | Kernel = rbf | Accuracy = 0.8769230769230769

In [51]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

parameters = {
    "C": [1, 10, 20],
    "kernel": ["linear", "rbf"]
}

grid = GridSearchCV(SVC(), parameters, cv=5)

grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']})

In [57]:
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Parameters: {'C': 20, 'kernel': 'linear'}
Best Score: 0.9325056011949217

In [56]:
results = pd.DataFrame(grid.cv_results_)
results[["param_C", "param_kernel", "mean_test_score"]]

   param_C param_kernel  mean_test_score
0        1       linear         0.932487
1        1          rbf         0.911352
2       10       linear         0.932487
3       10          rbf         0.920967
4       20       linear         0.932506
5       20          rbf         0.915217

In [58]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVC

parameters = {
    "C": [1, 10, 20],
    "kernel": ["linear", "rbf"]
}

random = RandomizedSearchCV(SVC(), parameters, n_iter=5, cv=5, random_state=42)

random.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=5,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['linear', 'rbf']},
                   random_state=42)

In [59]:
results = pd.DataFrame(random.cv_results_)
results[["param_C", "param_kernel", "mean_test_score"]]

   param_C param_kernel  mean_test_score
0        1       linear         0.932487
1        1          rbf         0.911352
2       20          rbf         0.915217
3       10       linear         0.932487
4       20       linear         0.932506

In [60]:
print("Best Parameters:", random.best_params_)
print("Best Score:", random.best_score_)

Best Parameters: {'kernel': 'linear', 'C': 20}
Best Score: 0.9325056011949217

In [62]:
from sklearn.ensemble import RandomForestClassifier
model_RF = RandomForestClassifier(n_estimators=100, random_state=42)
model_RF.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [83]:
from sklearn.metrics import accuracy_score
y_pred = model_RF.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)

Accuracy Score: 0.9076923076923077

In [65]:
from sklearn.ensemble import AdaBoostClassifier
model_AB = AdaBoostClassifier(n_estimators=100, random_state=42)
model_AB.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [66]:
from sklearn.metrics import accuracy_score
y_pred = model_AB.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)

Accuracy Score: 0.9307692307692308

In [67]:
from sklearn.ensemble import GradientBoostingClassifier
model_GB = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

model_GB.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [68]:
y_pred = model_GB.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)

Accuracy Score: 0.9153846153846154

In [69]:
from xgboost import XGBClassifier
model_XGB = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)
model_XGB.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [70]:
y_pred = model_XGB.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)

Accuracy Score: 0.9076923076923077

In [71]:
from sklearn.model_selection import GridSearchCV
parameters = {
    "n_estimators": [50, 100, 150],
    "max_depth": [3, 5, 7]
}

grid = GridSearchCV(RandomForestClassifier(random_state=42), parameters, cv=5)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [3, 5, 7],
                         'n_estimators': [50, 100, 150]})

In [72]:
results = pd.DataFrame(grid.cv_results_)
results[["param_n_estimators", "param_max_depth", "mean_test_score"]]

   param_n_estimators  param_max_depth  mean_test_score
0                  50                3         0.913219
1                 100                3         0.917084
2                 150                3         0.917084
3                  50                5         0.930564
4                 100                5         0.932487
5                 150                5         0.930583
6                  50                7         0.922872
7                 100                7         0.924813
8                 150                7         0.922872

In [73]:
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Parameters: {'max_depth': 5, 'n_estimators': 100}
Best Score: 0.9324869305451831

In [77]:
from sklearn.metrics import accuracy_score
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "SVM",
        "Random Forest",
        "AdaBoost",
        "Gradient Boosting",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_score(y_test, model_SVM.predict(X_test)),
        accuracy_score(y_test, model_RF.predict(X_test)),
        accuracy_score(y_test, model_AB.predict(X_test)),
        accuracy_score(y_test, model_GB.predict(X_test)),
        accuracy_score(y_test, model_XGB.predict(X_test))
    ]})
print(results)

               Model  Accuracy
0                SVM  0.876923
1      Random Forest  0.907692
2           AdaBoost  0.930769
3  Gradient Boosting  0.915385
4            XGBoost  0.907692

In [78]:
best = results.loc[results["Accuracy"].idxmax()]

print("Best Model :", best["Model"])
print("Best Accuracy :", best["Accuracy"])

Best Model : AdaBoost
Best Accuracy : 0.9307692307692308

In [79]:
import joblib
joblib.dump(model_RF, "best_model.pkl")
print("Model saved successfully.")

Model saved successfully.

In [80]:
import joblib
joblib.dump(scaler, "scaler.pkl")
print("Scaler saved successfully.")

Scaler saved successfully.